version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:${DB_NAME}
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_PASSWORD:${DB_USER_PASSWORD}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todoapi
    ports:
      - "8000:8000"
    depends_on:
      - db

